---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: demo

image: rancher/k3s:v1.28.7-k3s1
servers: 3
agents: 0

kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6445"

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer

  - port: 443:443
    nodeFilters:
      - loadbalancer

registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5000"

options:
  k3d:
    wait: true
    timeout: 1m
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    loadbalancer:
      configOverrides:
        - settings.workerConnections=2048

  k3s:
    extraArgs:
      - arg: --tls-san=demo-cluster.local
        nodeFilters:
          - server:*

    nodeLabels:
      - label: role=server
        nodeFilters:
          - server:*

  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
